"""
Django settings for student_learning_platform project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jhlmm9832t0av_84ksk-9+d%1@ov#5-qt_(y-9o*yj7oyx9$0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '172.25.50.161', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'exercises',
    'practice',
    'web',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'student_learning_platform.middleware.CorsDebugMiddleware',  # CORS调试中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'student_learning_platform.middleware.DebugMediaMiddleware',  # 媒体文件调试中间件
]

ROOT_URLCONF = 'student_learning_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]


WSGI_APPLICATION = 'student_learning_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS 配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://172.25.50.161:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境临时使用
CORS_ALLOW_HEADERS = ['*']  # 允许所有请求头
CORS_EXPOSE_HEADERS = ['*']  # 暴露所有响应头

# 确保媒体文件不会被认证拦截
CORS_URLS_REGEX = r'^/.*$'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True
  # 匹配所有URL

# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True


# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True
  # 匹配所有URL

# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True
  # 匹配所有URL

# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True


# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True
  # 匹配所有URL

# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your-secret-key-here',  # 生产环境应该使用环境变量
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# VL LLM API 配置
VLLM_API_CONFIG = {
    'default_url': 'https://api.siliconflow.cn/v1/chat/completions',
    'default_api_key': 'sk-hglnfzrlezgqtiionjdduvqrfmwfpjnkdksfizvnpseqvlwu',
    'default_model': 'Qwen/Qwen3-VL-32B-Instruct',
}

# 中文配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 禁用密码验证以降低密码要求（根据需求）
AUTH_PASSWORD_VALIDATORS = []

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 登录URL配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下提供静态文件服务
# 注意：这个配置在urls.py中处理

# 调试模式
DEBUG = True
