# Generated by Django 4.2.9 on 2025-11-30 10:35:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(max_length=100, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_avatar',
            field=models.URLField(max_length=500, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_nickname',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_way',
            field=models.CharField(max_length=10, default='password', choices=[
                ('password', '密码登录'),
                ('wechat', '微信登录'),
            ]),
        ),
    ]