# Generated by Django 4.2.7 on 2025-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_wechat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_way',
            field=models.CharField(choices=[('password', '密码登录'), ('wechat', '微信登录')], default='password', max_length=10, verbose_name='登录方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='微信头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信UnionID'),
        ),
    ]
