# Generated by Django 4.2.7 on 2025-11-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('api_url', models.URLField(verbose_name='API地址')),
                ('api_key', models.CharField(max_length=200, verbose_name='API密钥')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VL LLM配置',
                'verbose_name_plural': 'VL LLM配置',
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题目数')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='正确答案数')),
                ('score', models.FloatField(default=0, verbose_name='得分')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '练习会话',
                'verbose_name_plural': '练习会话',
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer_text', models.TextField(blank=True, verbose_name='学生答案')),
                ('student_answer_image', models.ImageField(blank=True, null=True, upload_to='uploads/answers/', verbose_name='学生答题图片')),
                ('status', models.CharField(choices=[('correct', '正确'), ('wrong', '错误'), ('skipped', '跳过')], max_length=10, verbose_name='答题状态')),
                ('response_time', models.IntegerField(help_text='响应时间（秒）', verbose_name='响应时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('llm_analysis', models.JSONField(blank=True, default=dict, verbose_name='LLM分析结果')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='习题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practicesession', verbose_name='练习会话')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePointMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0, verbose_name='掌握程度 (0-100)')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总尝试次数')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='正确次数')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='最后练习时间')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.knowledgepoint', verbose_name='知识点')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '知识点掌握程度',
                'verbose_name_plural': '知识点掌握程度',
                'unique_together': {('student', 'knowledge_point')},
            },
        ),
    ]
