# Generated by Django 4.2.7 on 2025-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vllmconfig',
            name='is_active',
            field=models.BooleanField(default=True, unique=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='vllmconfig',
            name='name',
            field=models.CharField(default='VL LLM配置', max_length=100, verbose_name='配置名称'),
        ),
    ]
