# Generated by Django 4.2.7 on 2025-11-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exampoint_grade_level_and_more'),
        ('practice', '0002_alter_vllmconfig_is_active_alter_vllmconfig_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicerecord',
            options={'ordering': ['session', 'question_number'], 'verbose_name': '练习记录', 'verbose_name_plural': '练习记录'},
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='points_earned',
            field=models.FloatField(default=0, verbose_name='获得分数'),
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='question_number',
            field=models.IntegerField(default=1, verbose_name='题目序号'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='response_time',
            field=models.IntegerField(help_text='响应时间（毫秒）', verbose_name='响应时间'),
        ),
        migrations.CreateModel(
            name='SessionKnowledgePointScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='该知识点题目数')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='该知识点答对数')),
                ('score', models.FloatField(default=0, verbose_name='知识点得分')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.knowledgepoint', verbose_name='知识点')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practicesession', verbose_name='练习会话')),
            ],
            options={
                'verbose_name': '练习会话知识点得分',
                'verbose_name_plural': '练习会话知识点得分',
                'unique_together': {('session', 'knowledge_point')},
            },
        ),
    ]
