# Generated by Django 4.2.7 on 2025-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_practicerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicerecord',
            name='status',
            field=models.CharField(choices=[('correct', '正确'), ('wrong', '错误'), ('skipped', '跳过'), ('pending', '待分析')], max_length=10, verbose_name='答题状态'),
        ),
    ]
