# Generated by Django 4.2.7 on 2025-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_practicerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicerecord',
            name='llm_analysis',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='LLM分析结果'),
        ),
    ]
