# Generated by Django 4.2.7 on 2025-11-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学科名称')),
                ('description', models.TextField(blank=True, verbose_name='学科描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识点名称')),
                ('description', models.TextField(blank=True, verbose_name='知识点描述')),
                ('grade_level', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')], verbose_name='适用年级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.knowledgepoint', verbose_name='父知识点')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'unique_together': {('name', 'subject', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='uploads/questions/', verbose_name='题目图片')),
                ('answer_text', models.TextField(verbose_name='标准答案')),
                ('answer_steps', models.TextField(verbose_name='解题步骤')),
                ('grade_level', models.IntegerField(verbose_name='适用年级')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总尝试次数')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='正确次数')),
                ('wrong_attempts', models.IntegerField(default=0, verbose_name='错误次数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('knowledge_points', models.ManyToManyField(to='exercises.knowledgepoint', verbose_name='相关知识点')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '习题',
                'verbose_name_plural': '习题',
            },
        ),
        migrations.CreateModel(
            name='StudentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer_text', models.TextField(blank=True, verbose_name='学生答案')),
                ('student_answer_image', models.ImageField(blank=True, null=True, upload_to='uploads/answers/', verbose_name='学生答题图片')),
                ('status', models.CharField(choices=[('correct', '正确'), ('wrong', '错误'), ('not_attempted', '未尝试')], default='not_attempted', max_length=20, verbose_name='答题状态')),
                ('is_mistake', models.BooleanField(default=True, verbose_name='是否为错题')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('llm_analysis', models.JSONField(blank=True, default=dict, verbose_name='LLM分析结果')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生错题记录',
                'verbose_name_plural': '学生错题记录',
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
