# Generated by Django 4.2.7 on 2025-11-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgepoint',
            name='parent',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, to='exercises.knowledgepoint', verbose_name='相关知识点'),
        ),
        migrations.CreateModel(
            name='ExamPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考点名称')),
                ('grade_level', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')], verbose_name='适用年级')),
                ('description', models.TextField(blank=True, verbose_name='考点描述')),
                ('difficulty_weight', models.FloatField(default=1.0, help_text='1.0-3.0，数值越大难度越高', verbose_name='难度系数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.knowledgepoint', verbose_name='所属知识点')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.subject', verbose_name='学科')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点',
                'unique_together': {('name', 'knowledge_point', 'grade_level')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exam_points',
            field=models.ManyToManyField(blank=True, to='exercises.exampoint', verbose_name='相关考点'),
        ),
    ]
