# Generated by Django 4.2.7 on 2025-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_knowledgepoint_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampoint',
            name='grade_level',
            field=models.CharField(choices=[('小学1年级', '小学1年级'), ('小学2年级', '小学2年级'), ('小学3年级', '小学3年级'), ('小学4年级', '小学4年级'), ('小学5年级', '小学5年级'), ('小学6年级', '小学6年级'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=10, verbose_name='适用年级'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='grade_level',
            field=models.CharField(choices=[('小学1年级', '小学1年级'), ('小学2年级', '小学2年级'), ('小学3年级', '小学3年级'), ('小学4年级', '小学4年级'), ('小学5年级', '小学5年级'), ('小学6年级', '小学6年级'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=10, verbose_name='适用年级'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='grade_level',
            field=models.CharField(choices=[('小学1年级', '小学1年级'), ('小学2年级', '小学2年级'), ('小学3年级', '小学3年级'), ('小学4年级', '小学4年级'), ('小学5年级', '小学5年级'), ('小学6年级', '小学6年级'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=10, verbose_name='适用年级'),
        ),
    ]
