# Generated by Django 4.2.7 on 2025-12-01 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_alter_exampoint_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='target_grade_levels',
            field=models.JSONField(blank=True, default=list, help_text='当可见性为"共享"时，指定的年级用户可以访问此题目', verbose_name='目标年级'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='当可见性为"共享"时，指定的用户可以访问此题目', related_name='shared_exercises', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='visibility',
            field=models.CharField(choices=[('private', '私人'), ('public', '公共'), ('shared', '共享')], default='private', max_length=10, verbose_name='可见性'),
        ),
    ]
