# Generated by Django 4.2.7 on 2025-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_target_grade_levels_exercise_target_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_solved',
            field=models.BooleanField(default=True, help_text='标记题目是否已有标准答案和解题步骤', verbose_name='是否已解答'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source',
            field=models.CharField(default='individual', help_text='题目来源：individual(个人上传), batch_upload(批量上传)', max_length=50, verbose_name='题目来源'),
        ),
    ]
